# FROM golang:1.22

# WORKDIR /usr/src/app

# # pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
# COPY go.mod go.sum ./
# RUN go mod download && go mod verify

# COPY . .
# RUN go build -v -o /usr/local/bin/app .

# CMD ["/usr/local/bin", "app"]

FROM golang:1.22 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
ENV CGO_ENABLED=1
RUN go build -o app main.go

FROM alpine

WORKDIR /build

COPY --from=builder /build/app /build/app

CMD ["/build/app"]